[package]
name = "shorebird_updater_network"
version = "0.1.0"
edition = "2021"

[lib]
# Android 使用动态库，iOS 使用静态库
crate-type = ["cdylib", "staticlib"]

[dependencies]
anyhow = { version = "1.0.69", features = [] }
base64 = "0.22.0"
bipatch = "1.0.0"
comde = { version = "0.2.3", default-features = false, features = ["zstandard"] }
dyn-clone = "1.0.16"
hex = "0.4.3"
http = "1.2.0"
libc = "0.2.98"
log = "0.4.14"
once_cell = "1.17.1"
pipe = "0.4.0"
reqwest = { version = "0.12", default-features = false, features = ["blocking", "json", "rustls-tls"] }
ring = "0.17.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.93"
serde_yaml = "0.9.19"
sha2 = "0.10.6"
url = "2.4.0"
zip = { version = "0.6.4", default-features = false, features = ["deflate"] }

[target.'cfg(target_os = "android")'.dependencies]
android_logger = "0.13.0"
log-panics = { version = "2", default-features = false }

[target.'cfg(any(target_os = "ios", target_os = "macos"))'.dependencies]
log-panics = { version = "2", features = ["with-backtrace"] }
oslog = "0.2.0"

[target.'cfg(any(target_os = "linux", target_os = "windows"))'.dependencies]
simple_logger = "5.0.0"

[build-dependencies]
cbindgen = "0.24.0"
